import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');

assert.match(html, /indexedDB\.open\('threnyx_secure_v3',3\)/, 'le schéma IndexedDB doit versionner le stockage agent');
assert.match(html, /'agents'/, 'les appairages agent doivent être stockés dans un store dédié chiffré');
assert.match(html, /const AgentBridge=\{/, 'le pont agent doit être explicitement isolé');
assert.match(html, /TAG:'THX-HERMES1'/, 'le format de grant doit être versionné');
assert.match(html, /TTL:10\*60e3/, 'le grant doit expirer en dix minutes');
assert.match(html, /await Secp\.sign\(digest,S\.me\.priv\)/, 'le grant doit être signé localement par l’identité Threnyx');
assert.match(html, /await Secp\.verify\(/, 'le format de grant doit pouvoir être vérifié cryptographiquement');
assert.match(html, /protocols:\['nip17'\]/, 'le grant doit limiter explicitement le transport au protocole NIP-17');
assert.match(html, /S\.contacts\.get\(pub\)\?\.agent/, 'les identités agent ne doivent jamais déclencher un lien P2P');
assert.match(html, /case 'agentAck':\{await AgentBridge\.acknowledge/, 'seul un accusé bot contrôlé doit activer l’état connecté');
assert.match(html, /AgentBridge\.can\(S\.activeChat,agentKind\)/, 'les pièces jointes doivent respecter les permissions agent');
assert.match(html, /AgentBridge\.can\(S\.activeChat,'voice'\)/, 'les vocaux doivent respecter les permissions agent');
assert.match(html, /agentRevoke/, 'la révocation doit notifier le bot sans attendre sa confirmation');
assert.match(html, /id="agent-open"/, 'les réglages doivent offrir un point d’entrée visible pour connecter un agent');
assert.match(html, /id="agent-image"/, 'le consentement image doit être explicite');
assert.match(html, /id="agent-file"/, 'le consentement fichier doit être explicite');
assert.match(html, /id="agent-voice"/, 'le consentement vocal doit être explicite');
assert.ok(!html.includes('id="agent-qr"'), 'le QR Hermes doit être retiré : le code copiable est le parcours supporté');
assert.ok(!html.includes("QR.draw($('#agent-qr')"), 'le code Hermes ne doit plus tenter de dessiner un QR instable');
assert.match(html, /COPIER LE GUIDE/, 'le guide de raccordement doit être copiable depuis le parcours');
assert.match(html, /const richText=s=>\{/, 'le rendu Markdown doit être isolé dans un moteur explicite');
assert.match(html, /const inline=value=>esc\(value\)/, 'le Markdown doit échapper le texte non fiable avant toute balise de formatage');
assert.match(html, /class="md-table"/, 'le sous-ensemble Markdown doit supporter des tableaux lisibles');
assert.match(html, /const AgentCommands=\{/, 'les commandes agent doivent être séparées du transport');
assert.match(html, /id="agent-commands"/, 'la saisie doit exposer une aide de commandes contextuelle');
assert.match(html, /id="btn-agent-commands"/, 'le chat agent doit offrir un accès tactile aux commandes');
assert.match(html, /agentManifest/, 'le catalogue de commandes doit pouvoir provenir du connecteur Hermes');
assert.match(html, /agentPrompt/, 'les choix et confirmations Hermes doivent être reçus comme prompts corrélés');
assert.match(html, /agentPromptResponse/, 'un bouton doit transmettre une réponse corrélée au connecteur');
assert.match(html, /agentPromptAck/, 'le connecteur doit confirmer explicitement le traitement d’une action interactive');
assert.match(html, /prompt_id/, 'les actions interactives doivent porter un identifiant opaque de prompt');
assert.match(html, /response_id/, 'les réponses aux boutons doivent avoir un identifiant de déduplication');
assert.match(html, /AgentBridge\.choosePrompt/, 'la pression d’un bouton ne doit déclencher que le transport agent');
assert.match(html, /prompt\.state!==\'sent\'/, 'un accusé ne doit être accepté que pour une réponse interactive encore en attente');
assert.ok(!html.includes('AgentCommands.handle(text)'), 'aucune commande, y compris /help, ne doit être exécutée localement');
assert.ok(!html.includes('GATEWAY_RELAY_SECRET'), 'la PWA ne doit jamais contenir un secret gateway Hermes');
assert.ok(!html.includes('GATEWAY_ALLOW_ALL_USERS'), 'la PWA ne doit jamais demander une autorisation Hermes ouverte');

console.log('hermes agent bridge checks: OK');
