#!/usr/bin/env python3
"""
THX-HERMES1 grant validation.
Decodes and verifies the pairing code generated by Threnyx.

Format: THX-HERMES1.<payload-base64url>.<signature-hex>

The payload is a JSON object with:
  - userPub: hex pubkey of the Threnyx user
  - botPub: hex pubkey of the bot (must match our bot identity)
  - permissions: list of strings (text, images, files, voice)
  - protocol: must be "nip17"
  - exp: unix timestamp expiration (max 10 min from issuance)
  - nonce: random string to prevent replay
  - id: unique grant identifier

Signature: BIP-340 Schnorr over SHA-256("threnyx/hermes-grant/v1:" + JSON-payload-exact)
"""
import base64
import hashlib
import json
import os
import tempfile
import time
from typing import Optional, Tuple, Dict, Any

from nostr_crypto import NostrKey


class GrantError(Exception):
    """Base exception for grant validation failures."""
    pass


class GrantExpiredError(GrantError):
    pass


class GrantSignatureError(GrantError):
    pass


class GrantBotMismatchError(GrantError):
    pass


class GrantReplayError(GrantError):
    pass


class GrantProtocolError(GrantError):
    pass


class GrantPermissionError(GrantError):
    pass


def b64url_decode(s: str) -> bytes:
    """Base64URL decode (with padding fix)."""
    s = s.replace('-', '+').replace('_', '/')
    padding = 4 - len(s) % 4
    if padding != 4:
        s += '=' * padding
    return base64.b64decode(s)


def b64url_encode(b: bytes) -> str:
    """Base64URL encode without padding."""
    return base64.urlsafe_b64encode(b).rstrip(b'=').decode('ascii')


def decode_grant_code(code: str) -> Tuple[dict, str, str]:
    """Decode a THX-HERMES1 grant code.

    Returns (payload_dict, signature_hex, payload_json_exact).
    Raises GrantError on malformed input.
    """
    parts = code.split('.')
    if len(parts) != 3:
        raise GrantError(f"invalid grant format: expected 3 parts, got {len(parts)}")

    prefix, payload_b64, sig_hex = parts

    if prefix != 'THX-HERMES1':
        raise GrantError(f"invalid grant prefix: {prefix}")

    # Decode payload
    try:
        payload_bytes = b64url_decode(payload_b64)
    except Exception as e:
        raise GrantError(f"invalid base64url payload: {e}")

    # The payload_json_exact is the decoded bytes as a string
    # This is what was signed — we must use it verbatim
    payload_json_exact = payload_bytes.decode('utf-8')

    try:
        payload = json.loads(payload_json_exact)
    except Exception as e:
        raise GrantError(f"invalid JSON payload: {e}")

    # Validate required fields — support both Threnyx format and test format
    # Threnyx uses: protocols (array), expiresAt (ms), permissions (object)
    # Test format uses: protocol (string), exp (s), permissions (list)
    required = ['userPub', 'botPub', 'permissions', 'id', 'nonce']
    for field in required:
        if field not in payload:
            raise GrantError(f"missing field: {field}")

    # Check for protocol field — either "protocols" (array) or "protocol" (string)
    if 'protocols' not in payload and 'protocol' not in payload:
        raise GrantError("missing field: protocol or protocols")

    # Check for expiration — either "expiresAt" (ms) or "exp" (s)
    if 'expiresAt' not in payload and 'exp' not in payload:
        raise GrantError("missing field: expiresAt or exp")

    return payload, sig_hex, payload_json_exact


def verify_grant_signature(payload_json_exact: str, sig_hex: str, user_pub: str) -> bool:
    """Verify the BIP-340 signature over the grant.

    The signing string is: "threnyx/hermes-grant/v1:" + JSON-payload-exact
    The hash is SHA-256 of that string.
    """
    signing_string = "threnyx/hermes-grant/v1:" + payload_json_exact
    msg_hash = hashlib.sha256(signing_string.encode('utf-8')).digest()
    sig = bytes.fromhex(sig_hex)

    if len(sig) != 64:
        raise GrantSignatureError(f"invalid signature length: {len(sig)}")

    return NostrKey.schnorr_verify(sig, msg_hash, user_pub)


class GrantValidator:
    """Validates and tracks THX-HERMES1 grants."""

    def __init__(self, bot_pub_hex: str, state_path: Optional[str] = None):
        self.bot_pub = bot_pub_hex
        self._consumed: Dict[str, dict] = {}
        self.state_path = os.path.abspath(state_path) if state_path else None
        self._load_state()

    def _load_state(self):
        if not self.state_path or not os.path.exists(self.state_path):
            return
        try:
            with open(self.state_path, encoding='utf-8') as handle:
                raw = json.load(handle)
            if not isinstance(raw, dict):
                raise ValueError('state must be a JSON object')
            for grant_id, record in raw.items():
                valid = (isinstance(grant_id, str) and isinstance(record, dict)
                         and isinstance(record.get('nonce_hash'), str)
                         and isinstance(record.get('user_pub'), str)
                         and isinstance(record.get('permissions'), list))
                if not valid:
                    raise ValueError('invalid persisted grant record')
            self._consumed = raw
        except (OSError, ValueError, json.JSONDecodeError) as exc:
            # A corrupt replay index must not silently authorize old grants.
            raise GrantError(f'cannot load durable grant state: {exc}') from exc

    def _persist_state(self):
        if not self.state_path:
            return
        directory = os.path.dirname(self.state_path)
        os.makedirs(directory, mode=0o700, exist_ok=True)
        fd, temporary_path = tempfile.mkstemp(prefix='.grants-', dir=directory, text=True)
        try:
            os.fchmod(fd, 0o600)
            with os.fdopen(fd, 'w', encoding='utf-8') as handle:
                json.dump(self._consumed, handle, sort_keys=True, separators=(',', ':'))
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_path, self.state_path)
            os.chmod(self.state_path, 0o600)
        except OSError as exc:
            try:
                os.unlink(temporary_path)
            except OSError:
                pass
            raise GrantError(f'cannot persist durable grant state: {exc}') from exc

    def validate(self, code: str, max_age_seconds: int = 600) -> dict:
        """Validate a THX-HERMES1 grant code.

        Returns the payload dict on success.
        Raises GrantError subclass on failure.
        """
        # Decode
        payload, sig_hex, payload_json_exact = decode_grant_code(code)

        # 1. Check bot identity
        if payload['botPub'] != self.bot_pub:
            raise GrantBotMismatchError(
                f"bot mismatch: grant for {payload['botPub']}, we are {self.bot_pub}"
            )

        # 2. Check protocol — Threnyx uses "protocols" (array) or "protocol" (string)
        protocols = payload.get('protocols', [])
        if isinstance(protocols, str):
            protocols = [protocols]
        if not protocols:
            protocols = [payload.get('protocol', '')]
        if 'nip17' not in protocols:
            raise GrantProtocolError(f"invalid protocol(s): {protocols}")

        # 3. Check expiration — Threnyx uses "expiresAt" in milliseconds
        # Also support "exp" in seconds for backward compat
        exp = payload.get('expiresAt')
        if exp is not None and exp > 1e12:
            exp = exp / 1000  # milliseconds to seconds
        if exp is None:
            exp = payload.get('exp')
        if exp is None:
            raise GrantExpiredError("no expiration field in grant")

        now = int(time.time())
        if now > exp:
            raise GrantExpiredError(
                f"grant expired: exp={exp}, now={now}"
            )

        # Also check it's not too far in the future
        if exp - now > max_age_seconds:
            raise GrantExpiredError(
                f"grant exp too far in future: {exp - now}s"
            )

        # 4. Verify signature
        if not verify_grant_signature(payload_json_exact, sig_hex, payload['userPub']):
            raise GrantSignatureError("invalid BIP-340 signature")

        # 5. Check replay — idempotent
        grant_id = payload['id']
        nonce_hash = hashlib.sha256(payload['nonce'].encode()).hexdigest()

        if grant_id in self._consumed:
            existing = self._consumed[grant_id]
            if existing['nonce_hash'] != nonce_hash:
                raise GrantReplayError(
                    f"grant id reused with different nonce: {grant_id}"
                )
            raise GrantReplayError(
                f"grant already consumed: {grant_id} (idempotent duplicate)"
            )

        # Check nonce hash hasn't been seen under a different grant id
        for gid, data in self._consumed.items():
            if data['nonce_hash'] == nonce_hash:
                raise GrantReplayError(
                    f"nonce reused under different grant: {gid}"
                )

        # 6. Normalize permissions — Threnyx uses an object {text: true, ...}
        # Also support a list ["text", ...] for backward compat
        raw_perms = payload.get('permissions', {})
        if isinstance(raw_perms, dict):
            perms_set = {k for k, v in raw_perms.items() if v}
        elif isinstance(raw_perms, list):
            perms_set = set(raw_perms)
        else:
            raise GrantPermissionError(f"invalid permissions format: {type(raw_perms)}")

        valid_perms = {'text', 'images', 'image', 'files', 'file', 'voice'}
        for perm in perms_set:
            if perm not in valid_perms:
                raise GrantPermissionError(f"unknown permission: {perm}")

        # Normalize singular/plural
        normalized = set()
        for p in perms_set:
            if p in ('image',):
                normalized.add('images')
            elif p in ('file',):
                normalized.add('files')
            else:
                normalized.add(p)

        if 'text' not in normalized:
            raise GrantPermissionError("grant must include 'text' permission")

        # A fresh user-authorized pairing replaces any older grant for this bot.
        self.revoke(payload['userPub'], persist=False)

        # Store normalized permissions in the payload
        payload['_normalized_permissions'] = sorted(normalized)

        # Mark as consumed
        self._consumed[grant_id] = {
            'nonce_hash': nonce_hash,
            'consumed_at': now,
            'user_pub': payload['userPub'],
            'permissions': sorted(normalized)
        }
        try:
            self._persist_state()
        except GrantError:
            del self._consumed[grant_id]
            raise

        return payload

    def get_active_grant(self, user_pub: str) -> Optional[dict]:
        """Get the active grant for a user, if any."""
        for grant_id, data in self._consumed.items():
            if data['user_pub'] == user_pub:
                return {
                    'id': grant_id,
                    'user_pub': user_pub,
                    'permissions': data['permissions'],
                    'consumed_at': data['consumed_at']
                }
        return None

    def revoke(self, user_pub: str, persist: bool = True):
        """Revoke all grants for a user."""
        to_remove = [
            gid for gid, data in self._consumed.items()
            if data['user_pub'] == user_pub
        ]
        for gid in to_remove:
            del self._consumed[gid]
        if persist:
            self._persist_state()

    def is_revoked(self, user_pub: str) -> bool:
        """Check if a user has no active grants."""
        return self.get_active_grant(user_pub) is None

    def has_permission(self, user_pub: str, permission: str) -> bool:
        """Check if a user has a specific permission."""
        grant = self.get_active_grant(user_pub)
        if not grant:
            return False
        return permission in grant['permissions']


def create_test_grant(user_key: NostrKey, bot_pub_hex: str,
                      permissions: list = None, exp_offset: int = 600) -> str:
    """Create a test THX-HERMES1 grant code (for testing only)."""
    import secrets as sec

    payload = {
        "userPub": user_key.pub_hex,
        "botPub": bot_pub_hex,
        "permissions": permissions or ["text"],
        "protocol": "nip17",
        "exp": int(time.time()) + exp_offset,
        "nonce": sec.token_hex(16),
        "id": f"grant-{sec.token_hex(8)}"
    }

    # Sign: SHA-256("threnyx/hermes-grant/v1:" + JSON-payload-exact)
    payload_json = json.dumps(payload, separators=(',', ':'))
    signing_string = "threnyx/hermes-grant/v1:" + payload_json
    msg_hash = hashlib.sha256(signing_string.encode('utf-8')).digest()
    sig = user_key.schnorr_sign(msg_hash)

    payload_b64 = b64url_encode(payload_json.encode('utf-8'))
    return f"THX-HERMES1.{payload_b64}.{sig.hex()}"
